# ============================================
# ls - List directory contents
# pwd - Print working directory
# cd - Change directory
# ============================================
ls # This command lists the files and directories in the current directory. You should see a list of items that are present in your current location.
ls -a # This command lists all files and directories, including hidden ones (those that start with a dot). You should see additional items in the output that were not visible with the previous ls command.
ls -l # This command lists files and directories in long format, providing detailed information such as
# permissions, number of links, owner, group, size, and modification date. The output will be more detailed compared to the basic ls command.
ls -la # This command combines the options of both -l and -a, showing all files and directories in long format. You will see a comprehensive list of all items in the current directory, along with detailed information about each item.
ls --all --long # This command is an alternative way to achieve the same result as ls -la. It uses the long-form options instead of the short-form options, but the output will be the same, showing all files and directories in long format.
ls -alh # This command lists all files and directories in long format with human-readable file sizes. The -h option makes the file sizes easier to read by using units like K (kilobytes), M (megabytes), and G (gigabytes) instead of just showing the size in bytes. The output will include all items in the current directory, along with detailed information and human-readable file sizes.
ls -alh --color=auto # This command lists all files and directories in long format with human-readable file sizes and colored output. The --color=auto option enables colorized output, which can help differentiate between different types of files and directories. The output will include all items in the current directory, along with detailed information, human-readable file sizes, and color coding for easier identification.
ls -alht # This command lists all files and directories in long format with human-readable file sizes, sorted by modification time (newest first). The -t option sorts the output by modification time, so you can easily see which files were modified most recently. The output will include all items in the current directory, along with detailed information, human-readable file sizes, and sorted by modification time.
ls -alh --color=auto --sort=time # This command is an alternative way to achieve the same result as ls -alht. It uses long-form options for both color and sorting, but the output will be the same, showing all files and directories in long format with human-readable file sizes, colored output, and sorted by modification time (newest first).
pwd # This command prints the current working directory, which is the directory you are currently in. The output will show the full path to your current location in the file system.
cd /home/username # This command changes your current directory to /home/username. You should replace "username" with your actual username on the system. After running this command, you will be in the /home/username directory, and you can verify this by running the pwd command again, which should now show /home/username as your current working directory.
cd .. # This command moves you up one level in the directory hierarchy. If you were previously in /home/username, running this command will take you to /home. You can verify this by running the pwd command again, which should now show /home as your current working directory. 
cd / # This command changes your current directory to the root directory, which is the top-level directory in the Linux file system. After running this command, you will be in the root directory, and you can verify this by running the pwd command again, which should now show / as your current working directory.
cd ~ # This command changes your current directory to your home directory. The tilde (~) is a shortcut that represents the path to your home directory. After running this command, you will be in your home directory, and you can verify this by running the pwd command again, which should now show the path to your home directory (e.g., /home/username) as your current working directory.
cd - # This command changes your current directory back to the previous directory you were in before the last cd command. For example, if you were in /home/username and then changed to /, running cd - will take you back to /home/username. You can verify this by running the pwd command again, which should show the previous directory as your current working directory.    
cd /mnt/c # This command changes your current directory to the C drive in WSL. After running this command, you will be in the /mnt/c directory, which corresponds to the C drive in Windows. You can verify this by running the pwd command again, which should now show /mnt/c as your current working directory.
cd /mnt/d # This command changes your current directory to the D drive in WSL. After running this command, you will be in the /mnt/d directory, which corresponds to the D drive in Windows. You can verify this by running the pwd command again, which should now show /mnt/d as your current working directory.
cd /mnt/e # This command changes your current directory to the E drive in WSL. After running this command, you will be in the /mnt/e directory, which corresponds to the E drive in Windows. You can verify this by running the pwd command again, which should now show /mnt/e as your current working directory.
cd /mnt/f # This command changes your current directory to the F drive in WSL. After running this command, you will be in the /mnt/f directory, which corresponds to the F drive in Windows. You can verify this by running the pwd command again, which should now show /mnt/f as your current working directory.
# Note: If you have other drives (like G: or H:), you can access them in WSL using the corresponding paths under /mnt/ (e.g., /mnt/g for G: drive). Always ensure that the drive you are trying to access is properly mounted in WSL and that you have the necessary permissions to access it.  
