# Linux File Timestamp : Modification Time, Access Time, Change Time
# =======================================================================
# In Linux, files have three important time stamps that provide information about the file's history and usage. These time stamps are:
# 1. Modification Time (mtime): This time stamp indicates when the file was last modified. It is updated whenever the contents of the file are changed. For example, if you edit a file and save the changes, the modification time will be updated to reflect the time of the last modification.
# 2. Access Time (atime): This time stamp indicates when the file was last accessed. It is updated whenever the file is read or accessed in any way, such as opening the file, reading its contents, or executing it. For example, if you open a file to read its contents, the access time will be updated to reflect the time of the last access.
# 3. Change Time (ctime): This time stamp indicates when the file's metadata was last changed. It is updated whenever there is a change to the file's metadata, such as changing permissions, ownership, or moving the file. For example, if you change the permissions of a file using the chmod command, the change time will be updated to reflect the time of the last metadata change.
# These time stamps can be viewed using the ls -l command, which shows the modification time by default. To view the access time and change time, you can use the ls -lu and ls -lc commands, respectively. Understanding these time stamps can help you track the history and usage of files in a Linux system, as well as troubleshoot issues related to file access and modifications.
ls -l # This command lists files and directories in long format, showing the modification time (mtime) by default. The output will include the file permissions, number of links, owner, group, size, and modification date for each item in the current directory.
ls -lu # This command lists files and directories in long format, showing the access time (atime) instead of the modification time. The output will include the file permissions, number of links, owner, group, size, and access date for each item in the current directory.
ls -lc # This command lists files and directories in long format, showing the change time (ctime) instead of the modification time. The output will include the file permissions, number of links, owner, group, size, and change date for each item in the current directory.
